version: '2'
services:
    points-app:
        image: points
        external_links:
            - points-mysql:mysql
            - points-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/points?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    points-mysql:
        extends:
            file: mysql.yml
            service: points-mysql
    points-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: points-elasticsearch
